<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Vault\Block\Form;

/**
 * @var Escaper $escaper
 * @var Form $block
 * @var SecureHtmlRenderer $secureRenderer
 */
$code = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>">
    <?php if ($options = $block->getChildHtml()) : ?>
        <select name="payment[public_hash]" id="<?= /* @noEscape */ $code ?>_public_hash"><?= /* @noEscape */ $options ?></select>
    <?php else : ?>
        <i><?= $escaper->escapeHtml(__('Not available')) ?></i>
    <?php endif; ?>
</fieldset>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    'display:none',
    'fieldset#payment_form_' . /* @noEscape */ $code
) ?>
