<?php

use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\View\TemplateEngine\Php $this */

$details = $block->getData(TokenUiComponentProviderInterface::COMPONENT_DETAILS);
?>
<option value="<?= $block->getData(TokenUiComponentProviderInterface::COMPONENT_PUBLIC_HASH) ?>">
    ending <?= $details['card'] ?> (<?= $details['type'] ?>, <?= $details['expiry'] ?>)
</option>
