<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Worldline\Connect\Block\Adminhtml\System\Config\Field\TestApiConnection;

/** @var TestApiConnection $block */
/** @var Escaper $escaper */
?>

<script>
    require([
        'jquery',
        'mage/translate',
        'prototype'
    ], function(jQuery, $t) {
        let testAPIConnectionSpan = jQuery('#<?= $escaper->escapeJs($block->getId()) ?>_result');

        jQuery('#<?= $escaper->escapeJs($block->getId()) ?>').click(function () {
            new Ajax.Request('<?= $escaper->escapeJs($block->getAjaxUrl()) ?>', {
                method: 'GET',
                loaderArea: false,
                asynchronous: true,
                onCreate: function() {
                    testAPIConnectionSpan.find('.success').hide();
                    testAPIConnectionSpan.find('.failure').hide();
                    testAPIConnectionSpan.find('.processing').show();
                    jQuery('#<?= $escaper->escapeJs($block->getId()) ?>_message').text('');
                },
                onSuccess: function(response) {
                    testAPIConnectionSpan.find('.processing').hide();
                    const resultText = JSON.parse(response.responseText);
                    testAPIConnectionSpan.find('.success').show();
                    jQuery('#<?= $escaper->escapeJs($block->getId()) ?>_message').text(resultText).css('color', 'green');
                },
                onFailure: function(response) {
                    testAPIConnectionSpan.find('.processing').hide();
                    testAPIConnectionSpan.find('.failure').show();
                    let resultText = $t('Something went wrong. Please check your account settings and try again.');
                    if (response.status === 422) {
                        resultText = JSON.parse(response.responseText);
                    }
                    jQuery('#<?= $escaper->escapeJs($block->getId()) ?>_message').text(resultText).css('color', 'red');
                }
            });
        });
    });
</script>

<?php echo $block->getButtonHtml() ?>
<span id="<?= $escaper->escapeJs($block->getId()) ?>_result">
    <img class="processing" hidden="hidden" alt="Testing API" style="margin:-1px 5px" src="<?= $escaper->escapeHtml($block->getViewFileUrl('images/process_spinner.gif')) ?>"/>
    <img class="success" hidden="hidden" alt="API test succeeded" style="margin:-3px 5px" src="<?= $escaper->escapeHtml($block->getViewFileUrl('images/rule_component_apply.gif')) ?>"/>
    <img class="failure" hidden="hidden" alt="API test failed" style="margin:-2px 5px" src="<?= $escaper->escapeHtml($block->getViewFileUrl('images/rule_component_remove.gif')) ?>"/>
    <br>
    <span id="<?= $escaper->escapeJs($block->getId()) ?>_message"></span>
</span>
